-- Create Database in Snowflake
CREATE DATABASE IMT577_DW_Mike_Wilson_M5;

-- Create DW in Snowflake
CREATE WAREHOUSE IMT577_Project_DW 
WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE;

